name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        command: buildozer android debug

    - name: Upload Artifact
      # This line has been updated from v3 to v4
      uses: actions/upload-artifact@v4
      with:
        name: AirQualityApp.apk
        path: bin/*.apk
